{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "\n",
    "class ContMissFiller(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        miss_cols = ['BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF',\n",
    "                 'Total Bsmt SF', 'Garage Area', 'Mas Vnr Area']\n",
    "        for col in miss_cols:\n",
    "            df[col] = df[col].fillna(df[col].mean())        \n",
    "        return df    \n",
    "    \n",
    "class LotFrontFiller(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        mean = df['Lot Frontage'].mean()\n",
    "        df['Lot Frontage'] = df.groupby(['MS SubClass'])['Lot Frontage'].apply(\n",
    "            lambda x:x.fillna(x.mean()))\n",
    "        df['Lot Frontage'] = df['Lot Frontage'].fillna(mean)\n",
    "        return df\n",
    "    \n",
    "class DiscMissFiller(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        miss_cols = ['Garage Cars', 'Bsmt Full Bath', 'Bsmt Half Bath']\n",
    "        for col in miss_cols:\n",
    "            df[col] = df[col].fillna(df[col].median()) \n",
    "            df[col] = df[col].astype(int)\n",
    "        return df\n",
    "    \n",
    "class GYBFiller(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):          \n",
    "        df = df.copy()\n",
    "        df['Garage Yr Blt'] = ames.groupby(['MS SubClass'])['Garage Yr Blt'].apply(\n",
    "            lambda x:x.fillna(x.median()))\n",
    "        df['Garage Yr Blt'] = df['Garage Yr Blt'].fillna(\n",
    "            df['Garage Yr Blt'].median())\n",
    "        df['Garage Yr Blt'] = df['Garage Yr Blt'].astype(int)\n",
    "        return df\n",
    "    \n",
    "class NaNExEncoder(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        likert_cols = ['Exter Qual', 'Exter Cond', 'Bsmt Qual', 'Bsmt Cond', \n",
    "                       'Heating QC', 'Kitchen Qual', 'Fireplace Qu', 'Garage Qual', \n",
    "                       'Garage Cond', 'Pool QC']\n",
    "        likert_dict = {'Ex': 9, 'Gd': 7, 'TA': 5, 'Fa': 3, 'Po': 2, np.nan: 0}\n",
    "        for col in likert_cols:\n",
    "            df[col] = [likert_dict[item] for item in df[col]]\n",
    "            df[col] = df[col].astype(int)\n",
    "        return df\n",
    "    \n",
    "class Ord2Encoder(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        ord2_cols = ['Lot Shape', 'Land Slope', 'Bsmt Exposure', 'BsmtFin Type 1',             \n",
    "             'BsmtFin Type 2', 'Central Air', 'Fence', 'Sale Condition']\n",
    "\n",
    "        ord2_dict = {'Reg':8, 'IR1':6, 'IR2':4, 'IR3':2, 'Gtl':9, 'Mod':6, 'Sev':3,\n",
    "                     'Gd':8, 'Av':6, 'Mn':4, 'No':2, 'GLQ':7, 'ALQ':6, 'BLQ':5, \n",
    "                     'Rec':4, 'LwQ':3, 'Unf':2, 'Y':10, 'N':5, 'GdPrv':8, 'MnPrv':6, \n",
    "                     'GdWo':4, 'MnWw':2, 'Normal':8, 'Abnorml':6, 'AdjLand':5, 'Alloca':4, \n",
    "                     'Family':3, 'Partial':2, np.nan:0\n",
    "                    }\n",
    "        for col2 in ord2_cols:\n",
    "            df[col2] = [ord2_dict[item] for item in df[col2]]\n",
    "        return df\n",
    "    \n",
    "class Ord3Encoder(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        ord3_cols = ['Functional', 'Garage Finish', 'Paved Drive']\n",
    "\n",
    "        ord3_dict = {'Typ':8, 'Min1':7, 'Min2':6, 'Mod':5, 'Maj1':4, 'Maj2':3, 'Sev':2, \n",
    "                     'Sal':1, 'Fin':9, 'RFn':6, 'Unf':3, 'Y':9, 'P':6, 'N':3, np.nan:0\n",
    "                    }        \n",
    "        for col3 in ord3_cols:\n",
    "            df[col3] = [ord3_dict[item] for item in df[col3]]\n",
    "        return df\n",
    "    \n",
    "class NominalFiller(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        nom_cols = ['Mas Vnr Type', 'Garage Type', 'Alley', 'Misc Feature']              \n",
    "        for col in nom_cols:\n",
    "            df[col] = df[col].fillna('None')\n",
    "        return df\n",
    "    \n",
    "class YrsRemodeler(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        df['Yrs_until_Remod'] = df['Year Remod/Add'] - df['Year Built']\n",
    "        return df\n",
    "    \n",
    "class ColDropper(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        drop_cols = ['Garage Area', '1st Flr SF', 'Garage Yr Blt', \n",
    "                     'TotRms AbvGrd']\n",
    "        for col in drop_cols:\n",
    "            df = df.drop(col, axis=1)        \n",
    "        return df\n",
    "    \n",
    "class DummyMaker(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        dumb_cols = ['MS SubClass', 'MS Zoning', 'Street', 'Alley', 'Land Contour', \n",
    "                     'Utilities', 'Lot Config', 'Neighborhood', 'Condition 1', \n",
    "                     'Condition 2', 'Bldg Type', 'House Style', 'Roof Style', \n",
    "                     'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', \n",
    "                     'Foundation', 'Heating', 'Electrical', 'Garage Type', \n",
    "                     'Misc Feature', 'Sale Type']\n",
    "        for col in dumb_cols:\n",
    "            dummies = pd.get_dummies(df[col], prefix=col)\n",
    "            df = pd.concat([df, dummies], axis=1)\n",
    "            df = df.drop([col], axis=1)      \n",
    "        return df\n",
    "    \n",
    "class OutlierCapper(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        cont_cols = ['Lot Frontage', 'Lot Area', 'Mas Vnr Area', 'BsmtFin SF 1', \n",
    "                     'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', '1st Flr SF',\n",
    "                     '2nd Flr SF', 'Gr Liv Area', 'Garage Area', 'Wood Deck SF', \n",
    "                     'Open Porch SF', 'Low Qual Fin SF', 'Enclosed Porch', \n",
    "                     '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Misc Val']\n",
    "        for col in cont_cols:\n",
    "            Q1 = df[col].quantile(0.25)\n",
    "            Q3 = df[col].quantile(0.75)\n",
    "            IQR = Q3 - Q1\n",
    "            LB = Q1 - (IQR * 1.5)\n",
    "            UB = Q3 + (IQR * 1.5)\n",
    "            df.loc[df[col] > UB, col] = UB\n",
    "            df.loc[df[col] < LB, col] = LB\n",
    "        return df\n",
    "    \n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "class DfStdScaler(BaseEstimator, TransformerMixin):    \n",
    "    def __init__(self):\n",
    "        self    \n",
    "        \n",
    "    def fit(self, df, y = None):               \n",
    "        return self\n",
    "\n",
    "    def transform(self, df):        \n",
    "        df = df.copy()\n",
    "        stdizer = StandardScaler()\n",
    "        std_cols = ['Lot Frontage', 'Lot Area', 'Mas Vnr Area', 'BsmtFin SF 1', \n",
    "                     'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', '1st Flr SF',\n",
    "                     '2nd Flr SF', 'Gr Liv Area', 'Garage Area', 'Wood Deck SF', \n",
    "                     'Open Porch SF', 'Low Qual Fin SF', 'Enclosed Porch', \n",
    "                     '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Misc Val',\n",
    "                   'Year Remod/Add', 'Yrs_until_Remod', 'Year Built']\n",
    "        df[std_cols] = stdizer.fit_transform(df[std_cols])\n",
    "        return df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
